openapi: 3.0.3
info:
  title: Swagger Car Tracker - OpenAPI 3.0
  description: This is a Car tracker Server based on the OpenAPI 3.0 specification.
  version: 1.0.11
servers:
- url: http://localhost:8080/
tags:
- name: car
  description: Rest APIs
paths:
  /car:
    post:
      tags:
      - car
      summary: add a new car
      description: Add a new car by Manufacturer
      operationId: createCar
      requestBody:
        description: Add a new car by Manufacturer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarDetails'
        "405":
          description: Invalid input
      x-swagger-router-controller: Car
    put:
      tags:
      - car
      summary: Update owner of an existing car
      description: Update owner of an existing car by Id
      operationId: updateCar
      requestBody:
        description: Add a new car by Manufacturer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferCar'
        required: true
      responses:
        "405":
          description: Invalid input
      x-swagger-router-controller: Car
      
  /car/{carId}:
    get:
      tags:
      - car
      summary: Find car by ID
      description: Returns a single car
      operationId: getCarById
      parameters:
      - name: carId
        in: path
        description: ID of car to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarDetails'
        "400":
          description: Invalid ID supplied
        "404":
          description: Car not found
      x-swagger-router-controller: Car
    
components:
  schemas:
    Car:
      type: object
      properties:
        model:
          type: string
          example: BMW
        dateManufactured:
          type: string
          example: '01/01/2023'
    
    CarDetails:
      type: object
      properties:
        carId:
          type: string
          example: 10000001
          
        model:
          type: string
          example: BMW
        dateManufactured:
          type: string
          example: '01/01/2023'  
        owner:
          type: string
          enum:
          - MANUFACTURER
          - DEALER
          - CUSTOMER
        status:
          type: string
          description: car status
          enum:
          - CREATED
          - READY_FOR_SALE
          - SOLD
    TransferCar:
      type: object
      properties:
        carId:
          type: string
          example: 10000001
        currentOwner:
          type: string
          enum:
          - MANUFACTURER
          - DEALER
        newOwner:
          type: string
          enum:
          - DEALER
          - CUSTOMER  
          
  requestBodies:
    Car:
      description: car object that needs to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Car'
